# .github/workflows/ci.yml
name: Build & Test

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  engine:
    name: C++ Engine
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: engine

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install C++ Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build build-essential clang-format-17

    - name: Check C++ Formatting
      run: find . -path ./vcpkg -prune -o -type f \( -name "*.cpp" -o -name "*.h" \) -print | xargs clang-format-17 --dry-run --Werror

    - name: Cache vcpkg binary cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/vcpkg/archives
        key: vcpkg-${{ hashFiles('engine/vcpkg.json') }}
        restore-keys: vcpkg-

    - name: Cache vcpkg installation
      uses: actions/cache@v4
      with:
        path: engine/vcpkg
        key: vcpkg-tool-${{ hashFiles('engine/vcpkg.json') }}
        restore-keys: vcpkg-tool-

    - name: Bootstrap Vcpkg
      working-directory: engine
      run: |
        if [ ! -f vcpkg/vcpkg ]; then
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          git -C vcpkg checkout 2025.04.09
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
        fi

    - name: Install C++ Dependencies with Vcpkg
      working-directory: engine
      run: ./vcpkg/vcpkg install --triplet x64-linux

    - name: Configure CMake
      working-directory: engine
      run: cmake -B build -G Ninja -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/engine/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build C++ Project
      working-directory: engine
      run: cmake --build build

    - name: Run C++ Tests
      working-directory: engine
      run: ctest --test-dir build --output-on-failure
